spring:
  application:
    name: wx-shop-order
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

wxshop:
  orderservice:
    version: 0.0.1

server:
  port: 8081

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    com.github.jaychenfe.order.mapper: trace

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.github.jaychenfe.order.service
