spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/wx_shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wxshop:
  redis:
    host: localhost
    port: 6379
