spring:
  application:
    name: wx-shop-main
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/wx_shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wxshop:
  redis:
    host: localhost
    port: 6379
  orderservice:
    version: 0.0.1
    url: ""

  dubbo:
    registry:
      address: zookeeper://localhost:2181
